// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newZealandWalksAPI.Data;

#nullable disable

namespace newZealandWalksAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20260120181414_Seeding data for Difficulties and for Regions entities.")]
    partial class SeedingdataforDifficultiesandforRegionsentities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("newZealandWalksAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("886ff909-1d37-4766-8a09-4ed126c3f5b5"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("64eff110-e6d7-4186-b395-d8abe8680776"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("463552a3-e133-47b1-b508-97645767a11b"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("newZealandWalksAPI.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35b76290-1889-4915-86cc-3534d77ed761"),
                            Code = "AUK",
                            Name = "Auckland",
                            RegionImageUrl = "https://i.pinimg.com/1200x/d0/fc/f3/d0fcf30de9d249ab8d02391fcc678cd2.jpg"
                        },
                        new
                        {
                            Id = new Guid("a06e1ddb-83bf-4ffc-aac1-7b7c4bf7f822"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://i.pinimg.com/736x/24/df/0e/24df0e95d0f76a668a680ccf0a88fcdb.jpg"
                        },
                        new
                        {
                            Id = new Guid("ae96acd9-49eb-480c-ab85-4a372e961227"),
                            Code = "QNT",
                            Name = "Queenstown",
                            RegionImageUrl = "https://i.pinimg.com/1200x/0a/d6/26/0ad62681527a91b9054c1a362cc64228.jpg"
                        },
                        new
                        {
                            Id = new Guid("213785ed-8bc9-46ac-84c4-885abe3583e8"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://i.pinimg.com/1200x/f8/8e/b4/f88eb4cc51cef11c92ad4fb0492673c7.jpg"
                        },
                        new
                        {
                            Id = new Guid("974a1b4e-939b-4dbb-b798-4a7924b947d0"),
                            Code = "HLZ",
                            Name = "Hamilton",
                            RegionImageUrl = "https://i.pinimg.com/1200x/e0/82/98/e08298d1c4f3d29b92c15265660c4b4b.jpg"
                        },
                        new
                        {
                            Id = new Guid("4f91fec9-4b07-4bf6-8d81-e6a7430f19c2"),
                            Code = "ROT",
                            Name = "Rotorua",
                            RegionImageUrl = "https://i.pinimg.com/1200x/a4/45/39/a44539536298c325706db782491167c3.jpg"
                        });
                });

            modelBuilder.Entity("newZealandWalksAPI.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks", "dbo");
                });

            modelBuilder.Entity("newZealandWalksAPI.Models.Domain.Walk", b =>
                {
                    b.HasOne("newZealandWalksAPI.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newZealandWalksAPI.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
